# launch_sweep_config.yaml
description: sweeps on launch quickstart
method: grid
run_cap: 10

# the training job
job: 'wandb/jobs/Example Train Job:latest'

# some parameters to tune
parameters:
  learning_rate:
    values: [0, 0.0001, 0.001, 0.01, 0.1, 1]
  epochs:
    max: 20
    min: 0
    distribution: int_uniform

# Optional Scheduler Params:
scheduler:
  num_workers: 8  # concurrent sweep runs
