# optuna_config_basic.yaml
description: An advanced configuration for an Optuna scheduler
job: # training job
run_cap: 5

metric:
  name: # <METRIC>
  goal: # maximize, minimize

scheduler:
  # TODO(gst): make public wandb entity Optuna Scheduler job
  job: griffin_wb/public/job-wandb_job_sweep_scheduler_optuna_latest:latest
  num_workers: 2
  settings:
    optuna_source: examples/launch/launch-sweeps/optuna-scheduler/optuna_wandb.py
