# optuna_config_basic.yaml
description: A basic configuration for an Optuna scheduler
job: griffin_wb/public/job-train_latest:latest
run_cap: 5

metric:
  name: val_acc
  goal: maximize

scheduler:
  # TODO(gst): replace with public wandb jobo
  job: griffin_wb/public/job-wandb_job_sweep_scheduler_optuna_latest:latest
  num_workers: 2
  settings:
    sampler:
      type: CmaEsSampler
      args:
        seed: 42
        n_startup_trials: 10
    pruner:
      type: PercentilePruner
      args:
        percentile: 25.0  # kill 75% of runs
        n_warmup_steps: 10  # pruning disabled for first x steps
