# optuna-config-basic.yaml
description: A basic configuration for an Optuna scheduler
job: 'wandb/jobs/Hello World 2:latest'
run_cap: 5

scheduler:
  job: 'wandb/jobs/job-OptunaScheduler:latest'
  num_workers: 2
  settings:
    sampler:
      type: CmaEsSampler
      args:
        seed: 42
        n_startup_trials: 10
    pruner:
      type: PercentilePruner
      args:
        percentile: 25.0  # kill 75% of runs
        n_warmup_steps: 10  # pruning disabled for first x steps