# optuna_config_basic.yaml
description: A basic configuration for an Optuna scheduler
# training job to run
job: wandb/sweep-jobs/job-fashion-MNIST-train:latest
run_cap: 5
metric:
  name: epoch/val_loss
  goal: minimize

scheduler:
  job: wandb/sweep-jobs/job-optuna-sweep-scheduler:latest
  resource: local-container  # required for scheduler jobs sourced from images
  num_workers: 2
  settings:
    pruner:
      type: PercentilePruner
      args:
        percentile: 25.0  # kill 75% of runs
        n_warmup_steps: 10  # pruning disabled for first x steps

parameters:
  learning_rate:
    min: 0.0001
    max: 1.0
