# optuna-config-basic.yaml
description: An advanced configuration for an Optuna scheduler
job: # training job
run_cap: 5

metric:
  name: # <METRIC>
  goal: # maximize, minimize

scheduler:
  job: 'griffin_wb/proj/job-OptunaScheduler:latest'
  num_workers: 2
  settings:
    optuna_source: examples/launch/launch-sweeps/optuna-scheduler/optuna_wandb.py
