program: train.py
method: bayes
metric:
    name: Validation/Accuracy
    goal: maximize
parameters:
    batch_size:
        values: [8, 16, 32]
    sample_points:
        values: [512, 1024, 2048]
    set_abstraction_ratio_1:
        min: 0.1
        max: 0.9
    set_abstraction_radius_1:
        min: 0.1
        max: 0.5
    set_abstraction_ratio_2:
        min: 0.1
        max: 0.9
    set_abstraction_radius_2:
        min: 0.1
        max: 0.5
    dropout:
        min: 0.1
        max: 0.7